config/routes.rb
Rails.application.routes.draw do
  
  resources :quotes do
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]
    end
  end
  devise_for :users
  resources :line_items, only: [:index, :show]
  resources :line_item_dates, only: [:index, :show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :compagny
    has_many :line_item_dates, dependent: :destroy
    has_many :line_items, through: :line_item_dates
    
    validates :name, presence: true

    scope :ordered, -> {order(id: :desc)}
    # Ex:- scope :active, -> {where(:active => true)}

    #after_create_commit -> { broadcast_prepend_to "quotes", partial: "quotes/quote", locals: { quote: self }, target: "quotes" }

    #after_create_commit -> { broadcast_prepend_later_to "quotes"}
    #after_update_commit -> { broadcast_replace_later_to "quotes"}
    #after_destroy_commit -> { broadcast_remove_to "quotes"}

    # Those three callbacks are equivalent to the following single line
    broadcasts_to ->(quote) {[quote.compagny, "quotes"]}, inserts_by: :prepend

    def total_price
        line_items.sum(&:total_price)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = current_compagny.quotes.ordered
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = current_compagny.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Le devis est bien crée ." }
      end
      else
        render :new, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Le devis a bien ete modifier ." }
      end
    else
    render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Le devis a bien ete supprimer ." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote

      # We must use current_company.quotes here instead of Quote
      # for security reasons
      @quote = current_compagny.quotes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:name)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%# app/views/quotes/_form.html.erb %>

<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
    <%= form_error_notification(quote) %>

    <%= f.input :name, input_html: { autofocus: true } %>
    <%= link_to "Annuler", quotes_path, class: "btn btn--light" %>

    <%= f.submit "Enregistrer", class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%# app/views/quotes/_quote.html.erb %>

<%= turbo_frame_tag quote do %>
    <div class="quote">
        <%= link_to quote.name, quote_path(quote),
        data:{turbo_frame: "_top"} %>
        <div class="quote__actions">
            <%= button_to "Supprimer",
                    quote_path(quote),
                    method: :delete,
                    class: "btn btn--light" %>
            <%= link_to "Modifier",
                  edit_quote_path(quote),
                  class: "btn btn--light" %>
        </div>
    </div>
<% end %>

app/views/quotes/_total.html.erb
<%# app/views/quotes/_total.html.erb %>

<footer class="quote-total">
    <div class="quote-total__inner container">
        <div>Total:</div>
        <div><%= number_to_currency quote.total_price %></div>
    </div>
</footer>

app/views/quotes/create.turbo_stream.erb
<%# app/views/quotes/destroy.turbo_stream.erb %>

<%# app/views/quotes/create.turbo_stream.erb %>

<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%# app/views/quotes/destroy.turbo_stream.erb %>

<%#= turbo_stream.remove "quote_#{@quote.id}" %>
<%= turbo_stream.remove @quote %>
<%= render_turbo_stream_flash_messages %>

<%# unless current_company.quotes.exists? %>
    <%#= turbo_stream.update Quote.new do %>
        <%#= render "shared/empty_state" %>
    <%# end %>
<%# end %>

app/views/quotes/edit.html.erb
<%# app/views/quotes/edit.html.erb %>

<main class="container">
<%= link_to sanitize("&larr; Retour aux devis"), quote_path(@quote) %>


    <div class="header">
        <h1>Modifier Devis</h1>
    </div>

    <%= turbo_frame_tag @quote do %>
        <%= render "form", quote: @quote %>
    <% end %>
</main>

app/views/quotes/index.html.erb
<%# This line generate the <turbo-cable-stream-source> tag %>
<%= turbo_stream_from current_compagny, "quotes" %>

<main class="container">

  <!-- Add Quote Header-->
  <div class="header">
    <h1>Devis</h1>

    <!-- New Quote Link -->
    <%= link_to 'Nouveau devis',new_quote_path,
        data:{turbo_frame: dom_id(Quote.new) }, 
        class:"btn btn--primary" %>
  </div>

  <!-- Add New Quote Form or Empty state if quote is none -->
  <%= turbo_frame_tag Quote.new do %>
      <% if @quotes.none? %>
          <%= render "shared/empty_state" %>
      <% end %>
  <% end %>


<%= turbo_frame_tag "quotes" do %>
    <%= render @quotes %>
<% end %>



    <!-- List Quotes -->
  <%#= turbo_frame_tag "quotes" do %>
    <%#= render "shared/empty_state_css" %>
    <%#= render @quotes %>
  <%# end %>
  
</main>

app/views/quotes/new.html.erb
<%# app/views/quotes/new.html.erb %>

<main class="container">
    
<%= link_to sanitize("&larr; Retour aux devis"), quotes_path %>


    <div class="header">
        <h1>Nouveau Devis</h1>
    </div>
    <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
    <% end %>
    
</main>

app/views/quotes/show.html.erb
<%# app/views/quotes/show.html.erb %>

<main class="container mb-xxxxl">

    <%= link_to sanitize("&larr; Retour aux devis"), quotes_path %>

    <div class="header">
        <h1>
            <%= @quote.name %>
        </h1>

        <%= link_to "Nouvelle Date",
                new_quote_line_item_date_path(@quote),
                data: { turbo_frame: dom_id(LineItemDate.new) },
                class: "btn btn--primary" %>
    </div>

    <%= turbo_frame_tag LineItemDate.new %>
    
    <%= turbo_frame_tag "line_item_dates" do %>
        <%= render @line_item_dates, quote: @quote %>
    <% end %>
</main>
<!-- Add Total Page-->
<%= turbo_frame_tag dom_id(@quote, :total) do %>
    <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/quotes/update.turbo_stream.erb
<%# app/views/quotes/destroy.turbo_stream.erb %>

<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>